---
- name: Install nginx
  apt: name=nginx state=present update_cache=true

- name: Copy across virtual host config
  template:
   src=templates/nginx.conf.j2
   dest=/etc/nginx/sites-available/{{url}}

- name: enable site
  file:
   src=/etc/nginx/sites-available/{{url}}
   dest=/etc/nginx/sites-enabled/{{url}}
   state=link
  notify:
    - reload nginx

- name: Remove default conf link
  file:
   path=/etc/nginx/sites-enabled/default
   state=absent
  notify:
    - reload nginx
